name: DreamDiffusion
version: '${project.version}'
author: 'cozmyc'
main: net.dreamdiffusion.dreamdiffusion.DreamDiffusionPlugin
api-version: '1.20'
depends: ['ImageFrame']
commands:
  dream:
    description: Generate an image with AI
  ddreload:
    description: Reload all settings
permissions:
  dreamdiffusion.use:
    description: Allows players to use /dream
    default: op
  dreamdiffusion.reload:
    description: Allows players to use /ddreload
    default: op